# Generated by Django 4.2.11 on 2024-04-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_menu_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='price',
            new_name='prince',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_item_description',
        ),
    ]
