# Generated by Django 4.2.11 on 2024-04-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_price_menu_prince_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='prince',
            new_name='price',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
